### ISSUE TITLE
Update symbolic dependencies to the latest version

### ISSUE THREAD

**Issue by gabrielesvelto** [mozilla/fix-stacks#38]
Ideally we should keep it in line with dump_syms which is currently using symbolic version 8.

**Comment by gabrielesvelto** [comment]
Note: this is also required to fix an issue which shows up when running tests in a debug build and which currently fail with the following stack trace
```
thread 'tests::test_regex' panicked at 'attempted to leave type `base::Symbol` uninitialized, which is invalid', /home/gsvelto/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:659:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
   3: core::mem::uninitialized
             at /home/gsvelto/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:659:9
   4: dmsort::dmsort::unsafe_push
             at /home/gsvelto/.cargo/registry/src/github.com-1ecc6299db9ec823/dmsort-1.0.0/src/dmsort.rs:219:11
   5: dmsort::dmsort::sort_move_by
             at /home/gsvelto/.cargo/registry/src/github.com-1ecc6299db9ec823/dmsort-1.0.0/src/dmsort.rs:280:5
   6: dmsort::dmsort::sort_by
             at /home/gsvelto/.cargo/registry/src/github.com-1ecc6299db9ec823/dmsort-1.0.0/src/dmsort.rs:355:2
   7: dmsort::dmsort::sort_by_key
             at /home/gsvelto/.cargo/registry/src/github.com-1ecc6299db9ec823/dmsort-1.0.0/src/dmsort.rs:369:2
   8: <symbolic_debuginfo::base::SymbolMap as core::convert::From<alloc::vec::Vec<symbolic_debuginfo::base::Symbol>>>::from
             at /home/gsvelto/.cargo/registry/src/github.com-1ecc6299db9ec823/symbolic-debuginfo-7.5.0/src/base.rs:376:13
   9: <T as core::convert::Into<U>>::into
             at /home/gsvelto/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs:546:9
  10: <symbolic_debuginfo::base::SymbolMap as core::iter::traits::collect::FromIterator<symbolic_debuginfo::base::Symbol>>::from_iter
             at /home/gsvelto/.cargo/registry/src/github.com-1ecc6299db9ec823/symbolic-debuginfo-7.5.0/src/base.rs:399:9
  11: core::iter::traits::iterator::Iterator::collect
             at /home/gsvelto/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/iter/traits/iterator.rs:1670:9
  12: symbolic_debuginfo::elf::ElfObject::symbol_map
             at /home/gsvelto/.cargo/registry/src/github.com-1ecc6299db9ec823/symbolic-debuginfo-7.5.0/src/elf.rs:221:9
  13: symbolic_debuginfo::elf::ElfObject::debug_session
             at /home/gsvelto/.cargo/registry/src/github.com-1ecc6299db9ec823/symbolic-debuginfo-7.5.0/src/elf.rs:242:23
  14: symbolic_debuginfo::object::Object::debug_session
             at /home/gsvelto/.cargo/registry/src/github.com-1ecc6299db9ec823/symbolic-debuginfo-7.5.0/src/object.rs:265:35
  15: fix_stacks::Fixer::build_file_info_direct
             at ./src/main.rs:416:29
  16: fix_stacks::Fixer::build_file_info
             at ./src/main.rs:329:32
  17: fix_stacks::Fixer::fix
             at ./src/main.rs:734:23
  18: fix_stacks::tests::test_regex::{{closure}}
             at ./src/tests.rs:422:28
  19: fix_stacks::tests::test_regex
             at ./src/tests.rs:425:5
  20: fix_stacks::tests::test_regex::{{closure}}
             at ./src/tests.rs:405:1
  21: core::ops::function::FnOnce::call_once
             at /home/gsvelto/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  22: core::ops::function::FnOnce::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/ops/function.rs:227:5
```
